name: 'Push directory to another repository'
description: 'Useful to push files to another repository to be used, for example, via github pages'
inputs:
  destination-github-username:
    description: 'Name of the destination username/organization'
    required: true
  user-email:
    description: 'Email for the git commit'
    required: true
  destination-branch:
    description: 'Destination branch'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.destination-github-username }}
    - ${{ inputs.user-email }}
    - ${{ inputs.destination-branch }}
branding:
  icon: 'git-commit'
  color: 'green'
