= Civet 

== Summary

=== Informasi Umum

Civet merupakan _clone_ dari sistem Pronghorn. Civet sendiri memiliki
_frontend_ yang dinamakan Robusta. Sistem ini merupakan sistem yang
berfungsi untuk memproses transaksi-transaksi _partner_ dari Whitelabel,
terutama dalam bidang telekomunikasi. Beberapa produk yang tersedia dan
dapat diproses oleh Civet adalah:  - Pulsa - Paket Data - dan lain-lain

Cara pembayaran yang dapat dilakukan dengan sistem Civet di antaranya
adalah: - Credit Card - Jenius - OVO - Kredivo - Gopay - Dana

Dalam memproses transaksi, sistem ini menerima order atau transaksi dari
_frontend_ Robusta, kemudian transaksi tersebut dilanjutkan dan diproses
di Kraken.

=== Latar Belakang Penamaan Sistem

Civet dalam bahasa Indonesia berarti musang. Musang adalah mamalia
bersifat nokturnal yang bertubuh kecil dan lentur. Sebagian besar
populasi musang berasal dari Asia dan Afrika, terutama daerah dengan
hutan tropis. Musang memiliki bentuk badan yang mirip seperti kucing,
dengan bentuk muka seperti luwak atau berang-berang. Panjang musang
dapat berkisar antara 43 hingga 71 meter (belum termasuk panjang ekor)
sedangkan beratya mencapai 1,4 hingga 4,5 kg.

=== Anggota Tim Civet


|===
|*Name* |*Role* |*Email*
|Pipit Puspitasari |Product Owner |pipit@alterra.id
|Ananto Eko Hendarto |Developer Manager |anton@alterra.id
|Kurniawan Eko Wasono |Lead Developer |iwan@alterra.id
|Johanes Paulus Giovani Putra |Lead Quality Engineer |johanes@alterra.id
|Pipit Puspitasari |Ex Lead System Analyst |pipit@alterra.id
|===

== Informasi Teknis

<<civet/url-civet.adoc#, Sytem Url Civet>>

<<civet/architecture-civet.adoc#, Architecture Civet>>

<<civet/technology-civet.adoc#, Technology Civet>>

<<civet/environment-civet.adoc#, Environment Civet>>

<<civet/database-documentation-civet.adoc#, Database Civet>>

<<civet/release-deployment-civet.adoc#, Release and Deployment Civet>>


== Onboarding Information

<<civet/developer-onboarding-civet.adoc#, Developer Onboarding Civet>>

<<civet/development-civet.adoc#, Development Civet>>

<<civet/naming-convention-civet.adoc#, Naming Convention Civet>>


== Dokumentasi

https://pron.sumpahpalapa.com/swaggerui/index.html[API Documentation]

https://github.com/sepulsa/civet/releases[Release Note]

<<civet/adr-doc.adoc#, Document ADR>>
