= Xpander

== Overview Test2

Xpander adalah platform untuk mengelola transaksi pembelian pulsa dan
paket data dari melalui system kita yang akan kita hubungkan ke Biller.
Xpander memungkinkan tim operasional untuk melakukan pendataan status
order dari Partner ataupun Biller.Untuk saat ini, Platform Xpander hanya
bisa digunakan untuk produk isi pulsa , paket data dan game voucher.

=== Anggota Tim Xpander

|===
|*Name* |*Role* |*Email*
|Pipit Puspitasari |Product Owner |pipit@alterra.id
|Ananto Eko Hendarto |Developer Manager |anton@alterra.id
|Kurniawan Eko Wasono |Lead Developer |iwan@alterra.id
|Johanes Paulus Giovani Putra |Lead Quality Engineer |johanes@alterra.id
|Pipit Puspitasari |Ex Lead System Analyst |pipit@alterra.id
|===

=== Informasi Teknis

<<xpander/url-xpander.adoc#, System Url Xpander>>

<<xpander/technology-xpander.adoc#, Technology Xpander>>

<<xpander/environment-xpander.adoc#, Environment Xpander>>


=== *Onboarding Information*
<<xpander/dev-onboardig-xpander.adoc#, Developer Onboarding Xpander>>

=== *Documentation*

<<xpander/katalog-proses-xpander.adoc#, Katalog Process Xpander>>

// <<xpander/xpander.adoc#, User Guide>>

<<xpander/adr-doc.adoc#, Document ADR Xpander>>
