# This CI should run after mergin from Pull Request (after editing)

name: Push Back to System Repo

on:
  push:
    branch: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: rochmadnurdin/knowledgebase@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs'
          destination-github-username: 'rochmadnurdin'
          destination-repository-name: 'knowledgebase'
          user-email: dev@alterra.id
          destination-branch: master
          system-name: SYSTEM

